#!/bin/bash

MACHINE=$1
REPONAME=$2

# List all git repos on a remote
DIRNAME="\"${REPONAME}.git\""

CMDS="cd ~/ && \
mkdir -p git/ &&
cd git/ && if [ -e $DIRNAME ]; \
then echo 'Repo Already Exists!'; \
else mkdir $DIRNAME && cd $DIRNAME && git init --bare && echo Created repo $DIRNAME; \
fi"

ssh $1 $CMDS